// Name: Ayushi Ujawane-10365
// Practical 6 - Q2: Sum of even numbers using continue

#include <stdio.h>

int main() {
    int n, sum = 0;
    printf("Enter number: ");
    scanf("%d", &n);

    for (int i = 1; i <= n; i++) {
        if (i % 2 != 0)
            continue;  
        sum += i;
    }

    printf("Sum of even numbers = %d", sum);
    return 0;
}

/*
OUTPUT:
Enter range: 10
Sum of even numbers = 30
*/
